version: "3.7"
services:
    react:
        image: react
        container_name: React
        build:
            context: ./FE
            dockerfile: Dockerfile
        ports:
            - 3000:3000
    nest:
        image: nest
        container_name: Nest
        build:
            context: ./BE
            dockerfile: Dockerfile
        ports:
            - 5000:5000